backend:
  name: github
  repo: josmiguel92/activasheweb #replace with your githu repo
  branch: main
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://activashecuba.org" # your site name

collections:
  - name: post
    label: Posts
    folder: src/content/posts
    create: true
    format: frontmatter
    preview_path: post/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: publishedAt, label: Date, widget: date }
      - {label: "Publish", name: "isPublish", widget: "boolean", default: true}
      - {label: "Draft", name: "isDraft", widget: "boolean", default: false}
      - { name: body, label: Body, widget: markdown }

  - name: project
    label: Projects
    folder: src/content/projects
    create: true
    format: frontmatter
    preview_path: projects/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: publishedAt, label: Date, widget: date }
      - { name: slug, label: Slug }
      - {label: "Publish", name: "isPublish", widget: "boolean", default: true}
      - { name: areas, label: Areas, widget: list, default: ["Investigaci√≥n", "Derechos Humanos"] }
      - {label: "Coming Soon", name: "isComingSoon", widget: "boolean", default: false}
      - { name: body, label: Body, widget: markdown }